spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sdm?serverTimezone=UTC
    username: root
    password: rootroo

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    ROOT: ERROR
    com.sarbootcamp: DEBUG
    org.springframework: ERROR
    org.springframework.boot.context.config: DEBUG
    org.springframework.data: DEBUG
    org.springframework.web.method.support: TRACE
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
  pattern:
    console: "%d %-5level %logger : %msg%n"

